[project]
name = "hcai_workbench"
version = "1.0.0"
description = "Chat interface for ai.hackclub.com"
authors = [
	{ name = "Paya Maroufi", email = "h2o.Drop2010+github@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.16"

dependencies = [
	"rich>=15.0.0,<16.0.0",
	"animation==0.0.7"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Communications :: Chat",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
	"build (>=1.4.0,<2.0.0)",
	"flake8 (>=7.3.0,<7.4.0)",
	"pytest (>=9.0.2,<10.0.0)",
	"twine (>=6.2.0,<7.0.0)",
	"wheel (>=0.47.0,<0.48.0)",
	"pyinstaller (>=6.21.0,<7.0.0)",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
